config/routes.rb
Rails.application.routes.draw do

  resources :transcript_seqs

  get 'protein_seqs/index'
  get 'protein_seqs', to: 'protein_seqs#index'

  get 'proteins/index'
  get 'proteins', to: 'proteins#index'

  get 'data_display/start_ids'
  get 'data_display', to: 'data_display#start_ids'

  get 'tattributes/index'
  get 'tattributes', to: 'tattributes#index'

  get 'transcripts/index'
  get 'transcripts', to: 'transcripts#index'
  
  get 'attributes/index'
  get 'attributes', to: 'attributes#index'

  get 'attributes/:id', to: 'attributes#show'

  get  'genes/gene_find'
  post 'genes/gene_find'
  get  'genes/index'
  get  'genes', to: 'genes#index'
  post 'genes', to: 'genes#index'

  get  'genes/:id', to: 'genes#show'
  post 'genes/:id', to: 'genes#show'

#  get  'dbpaths/show/:id',    to: 'dbpaths#show',    as: :galleries_show
  resources :dbpaths

   get 'mafft/align'
  post 'mafft/alignout'

  get  'blast/search', to: 'blast#search'
  post 'blast/blastout' => "blast/blastout"

  root 'static_pages#home'
  get  '/home',    to: 'static_pages#home'
  get  '/search',  to: 'static_pages#search'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup', to: 'users#new'
  resources :users

  get  'galleries/new/:id',    to: 'galleries#new',    as: :galleries_new
  get  'galleries/show/:id',        to: 'galleries#show' 

  get   'galleries/edit/:id',  to: 'galleries#edit' 
  patch 'galleries/edit/:id',  to: 'galleries#update' 

  get  'galleries/viewer/:id', to: 'galleries#viewer', as: :galleries_viewer
  get  'galleries/create',     to: 'galleries#create'
  get  'galleries/catalog',    to: 'galleries#catalog'

#  resources :galleries, only: [;create, :new, :edit, :update]
  resources :galleries

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attribute.rb
class Attribute < ApplicationRecord
end

app/models/dbpath.rb
class Dbpath < ApplicationRecord
end

app/models/gallery.rb
class Gallery < ApplicationRecord
end

app/models/gene.rb
class Gene < ApplicationRecord

  def to_fasta( seqid, sequence, num )
    output  = ""
    output += ">#{seqid}\n"
    sequence.split("").each_with_index do |n, i|
      if (i + 1) % num == 0
        output += "#{n}\n"
      else
        output += "#{n}"
      end
    end
    return output
  end



  private

  def to_fasta( seqid, sequence, num )
    output  = ""
    output += ">#{seqid}\n"
    sequence.split("").each_with_index do |n, i|
      if (i + 1) % num == 0
        output += "#{n}\n"
      else
        output += "#{n}"
      end
    end
    return output
  end


end

app/models/protein.rb
class Protein < ApplicationRecord
end

app/models/protein_seq.rb
class ProteinSeq < ApplicationRecord
end

app/models/tattribute.rb
class Tattribute < ApplicationRecord
end

app/models/transcript.rb
class Transcript < ApplicationRecord
end

app/models/transcript_seq.rb
class TranscriptSeq < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord

  validates :name, presence: true, length: { maximum: 50 }
  validates :role, presence: true, length: { maximum: 10 }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def blast
  end

  def gallery
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/attributes_helper.rb
module AttributesHelper
end

app/helpers/blast_helper.rb
module BlastHelper
end

app/helpers/dbpaths_helper.rb
module DbpathsHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/genes_helper.rb
module GenesHelper
end

app/helpers/mafft_helper.rb
module MafftHelper
end

app/helpers/proteins_helper.rb
module ProteinsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>RF Genome Browser</h1>
<p>
  <a href="#">Regional Fish Genome Browser Tutorial</a>.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  This is the genome browser by the
  <a href="https://regional.fish/">Regional Fish</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help /  Q&A </h1>
<p>
  now under construction
</p>

<h3> List of the view pages for the original data registered </h3>
<br><br>
  <li><a href="http://52.199.72.224/genes">Genes</a><br><br>
  <li><a href="http://52.199.72.224/transcripts">Transcripts</a><br><br>
  <li><a href="http://52.199.72.224/transcript_seqs">Transcript_seqs</a><br><br>
  <li><a href="http://52.199.72.224/proteins">Proteins</a><br><br>
  <li><a href="http://52.199.72.224/protein_seqs">Protein_seqs</a><br><br>
  <li><a href="http://52.199.72.224/dbpaths">Dbpaths</a><br><br>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>RF Genome Browser</h1>

  <h2>
    This is the genome browser by the
    <a href="https://regional.fish/">Regional Fish</a>.
  </h2>


  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

<%= link_to image_tag("rf.logo.png", alt: "RF logo", width: "200px"),
                      "https://regional.fish/" %>

app/views/static_pages/search.html.erb
<p>
  <%= link_to 'Blast Search', blast_search_path(:project_id => params[:project_id]) %>

</p>
<!-- <p>
  <%= link_to 'Mafft Search', mafft_align_path %>
</p> -->