config/routes.rb
Rails.application.routes.draw do

  resources :transcript_seqs

  get 'protein_seqs/index'
  get 'protein_seqs', to: 'protein_seqs#index'

  get 'proteins/index'
  get 'proteins', to: 'proteins#index'

  get 'data_display/start_ids'
  get 'data_display', to: 'data_display#start_ids'

  get 'tattributes/index'
  get 'tattributes', to: 'tattributes#index'

  get 'transcripts/index'
  get 'transcripts', to: 'transcripts#index'
  
  get 'attributes/index'
  get 'attributes', to: 'attributes#index'

  get 'attributes/:id', to: 'attributes#show'

  get  'genes/gene_find'
  post 'genes/gene_find'
  get  'genes/index'
  get  'genes', to: 'genes#index'
  post 'genes', to: 'genes#index'

  get  'genes/:id', to: 'genes#show'
  post 'genes/:id', to: 'genes#show'

#  get  'dbpaths/show/:id',    to: 'dbpaths#show',    as: :galleries_show
  resources :dbpaths

   get 'mafft/align'
  post 'mafft/alignout'

  get  'blast/search', to: 'blast#search'
  post 'blast/blastout' => "blast/blastout"

  root 'static_pages#home'
  get  '/home',    to: 'static_pages#home'
  get  '/search',  to: 'static_pages#search'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup', to: 'users#new'
  resources :users

  get  'galleries/new/:id',    to: 'galleries#new',    as: :galleries_new
  get  'galleries/show/:id',        to: 'galleries#show' 

  get   'galleries/edit/:id',  to: 'galleries#edit' 
  patch 'galleries/edit/:id',  to: 'galleries#update' 

  get  'galleries/viewer/:id', to: 'galleries#viewer', as: :galleries_viewer
  get  'galleries/create',     to: 'galleries#create'
  get  'galleries/catalog',    to: 'galleries#catalog'

#  resources :galleries, only: [;create, :new, :edit, :update]
  resources :galleries

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attribute.rb
class Attribute < ApplicationRecord
end

app/models/dbpath.rb
class Dbpath < ApplicationRecord
end

app/models/gallery.rb
class Gallery < ApplicationRecord
end

app/models/gene.rb
class Gene < ApplicationRecord

  def to_fasta( seqid, sequence, num )
    output  = ""
    output += ">#{seqid}\n"
    sequence.split("").each_with_index do |n, i|
      if (i + 1) % num == 0
        output += "#{n}\n"
      else
        output += "#{n}"
      end
    end
    return output
  end



  private

  def to_fasta( seqid, sequence, num )
    output  = ""
    output += ">#{seqid}\n"
    sequence.split("").each_with_index do |n, i|
      if (i + 1) % num == 0
        output += "#{n}\n"
      else
        output += "#{n}"
      end
    end
    return output
  end


end

app/models/protein.rb
class Protein < ApplicationRecord
end

app/models/protein_seq.rb
class ProteinSeq < ApplicationRecord
end

app/models/tattribute.rb
class Tattribute < ApplicationRecord
end

app/models/transcript.rb
class Transcript < ApplicationRecord
end

app/models/transcript_seq.rb
class TranscriptSeq < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord

  validates :name, presence: true, length: { maximum: 50 }
  validates :role, presence: true, length: { maximum: 10 }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

end

app/controllers/transcript_seqs_controller.rb
class TranscriptSeqsController < ApplicationController
  before_action :set_transcript_seq, only: %i[ show edit update destroy ]

  # GET /transcript_seqs or /transcript_seqs.json
  def index
#    @transcript_seqs = TranscriptSeq.all
    #
    @maxtransc_seqid = TranscriptSeq.maximum(:id)

    if params[:project_id] != nil
      @data_pages = TranscriptSeq.where(" project_id = ? ", params[:project_id] ).page params[:page]
    else
      @data_pages = TranscriptSeq.page params[:page]
    end
  end

  # GET /transcript_seqs/1 or /transcript_seqs/1.json
  def show
    @fasta_out = `ruby lib/assets/to_fasta.rb           \
                       #{@transcript_seq.nuc_sequence}  \
                       #{@transcript_seq.transcript_id}  `
  end

  # GET /transcript_seqs/new
  def new
    @transcript_seq = TranscriptSeq.new
  end

  # GET /transcript_seqs/1/edit
  def edit
  end

  # POST /transcript_seqs or /transcript_seqs.json
  def create
    @transcript_seq = TranscriptSeq.new(transcript_seq_params)

    respond_to do |format|
      if @transcript_seq.save
        format.html { redirect_to @transcript_seq, notice: "Transcript seq was successfully created." }
        format.json { render :show, status: :created, location: @transcript_seq }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @transcript_seq.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transcript_seqs/1 or /transcript_seqs/1.json
  def update
    respond_to do |format|
      if @transcript_seq.update(transcript_seq_params)
        format.html { redirect_to @transcript_seq, notice: "Transcript seq was successfully updated." }
        format.json { render :show, status: :ok, location: @transcript_seq }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @transcript_seq.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transcript_seqs/1 or /transcript_seqs/1.json
  def destroy
    @transcript_seq.destroy
    respond_to do |format|
      format.html { redirect_to transcript_seqs_url, notice: "Transcript seq was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transcript_seq
      @transcript_seq = TranscriptSeq.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def transcript_seq_params
      params.require(:transcript_seq).permit(:project_id, :transcript_id, :nuc_sequence)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title = '')
    base_title = "RF Genome Browser"
    if page_title.empty?
      base_title
    else
      page_title + "|" + base_title
    end
  end
end

app/helpers/attributes_helper.rb
module AttributesHelper
end

app/helpers/blast_helper.rb
module BlastHelper
end

app/helpers/dbpaths_helper.rb
module DbpathsHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/genes_helper.rb
module GenesHelper
end

app/helpers/mafft_helper.rb
module MafftHelper
end

app/helpers/proteins_helper.rb
module ProteinsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/transcript_seqs_helper.rb
module TranscriptSeqsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/transcript_seqs/_form.html.erb
<%= form_with(model: transcript_seq) do |form| %>
  <% if transcript_seq.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transcript_seq.errors.count, "error") %> prohibited this transcript_seq from being saved:</h2>

      <ul>
        <% transcript_seq.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :project_id %>
    <%= form.number_field :project_id %>
  </div>

  <div class="field">
    <%= form.label :transcript_id %>
    <%= form.text_field :transcript_id %>
  </div>

  <div class="field">
    <%= form.label :nuc_sequence %>
    <%= form.text_area :nuc_sequence %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/transcript_seqs/edit.html.erb
<h1>Editing Transcript Seq</h1>

<%= render 'form', transcript_seq: @transcript_seq %>

<%= link_to 'Show', @transcript_seq %> |
<%= link_to 'Back', transcript_seqs_path %>

app/views/transcript_seqs/index.html.erb
<p id="notice"><%= notice %></p>


<h1>Transcript Seqs</h1>

<p><%= @msg %> The last Trarnscript Seq ID: <%= @maxtransc_seqid  %></p>
<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Project</th>
      <th>Transcript</th>
      <th>Nuc sequence</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <% @data_pages.each do |transcript_seq| %>
      <tr>
        <td><%= transcript_seq.id %></td>
        <td><%= transcript_seq.project_id %></td>
        <td><%= transcript_seq.transcript_id %></td>
        <td><%= transcript_seq.nuc_sequence.size %></td>
        <td><%= link_to 'Show', transcript_seq %></td>
        <td><%= link_to 'Edit', edit_transcript_seq_path(transcript_seq) %></td>
        <td><%# = link_to 'Destroy', transcript_seq, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<br>
<div><%= paginate @data_pages %></div>
<br>

<%# = link_to 'New Transcript Seq', new_transcript_seq_path %>

app/views/transcript_seqs/new.html.erb
<h1>New Transcript Seq</h1>

<%= render 'form', transcript_seq: @transcript_seq %>

<%= link_to 'Back', transcript_seqs_path %>

app/views/transcript_seqs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Project:</strong>
  <%= @transcript_seq.project_id %>
</p>

<p>
  <strong>Transcript:</strong>
  <%= @transcript_seq.transcript_id %>
</p>

<p>
  <strong>Nuc sequence length:</strong>
  <%= @transcript_seq.nuc_sequence.size %>
</p>

<p>
  <strong>Nuc sequence:</strong>
  <pre><%= @fasta_out %></pre>
</p>


<%= link_to 'Edit', edit_transcript_seq_path(@transcript_seq) %> |
<%= link_to 'Back', transcript_seqs_path %>