config/routes.rb
Rails.application.routes.draw do

  resources :transcript_seqs

  get 'protein_seqs/index'
  get 'protein_seqs', to: 'protein_seqs#index'

  get 'proteins/index'
  get 'proteins', to: 'proteins#index'

  get 'data_display/start_ids'
  get 'data_display', to: 'data_display#start_ids'

  get 'tattributes/index'
  get 'tattributes', to: 'tattributes#index'

  get 'transcripts/index'
  get 'transcripts', to: 'transcripts#index'
  
  get 'attributes/index'
  get 'attributes', to: 'attributes#index'

  get 'attributes/:id', to: 'attributes#show'

  get  'genes/gene_find'
  post 'genes/gene_find'
  get  'genes/index'
  get  'genes', to: 'genes#index'
  post 'genes', to: 'genes#index'

  get  'genes/:id', to: 'genes#show'
  post 'genes/:id', to: 'genes#show'

#  get  'dbpaths/show/:id',    to: 'dbpaths#show',    as: :galleries_show
  resources :dbpaths

   get 'mafft/align'
  post 'mafft/alignout'

  get  'blast/search', to: 'blast#search'
  post 'blast/blastout' => "blast/blastout"

  root 'static_pages#home'
  get  '/home',    to: 'static_pages#home'
  get  '/search',  to: 'static_pages#search'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup', to: 'users#new'
  resources :users

  get  'galleries/new/:id',    to: 'galleries#new',    as: :galleries_new
  get  'galleries/show/:id',        to: 'galleries#show' 

  get   'galleries/edit/:id',  to: 'galleries#edit' 
  patch 'galleries/edit/:id',  to: 'galleries#update' 

  get  'galleries/viewer/:id', to: 'galleries#viewer', as: :galleries_viewer
  get  'galleries/create',     to: 'galleries#create'
  get  'galleries/catalog',    to: 'galleries#catalog'

#  resources :galleries, only: [;create, :new, :edit, :update]
  resources :galleries

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attribute.rb
class Attribute < ApplicationRecord
end

app/models/dbpath.rb
class Dbpath < ApplicationRecord
end

app/models/gallery.rb
class Gallery < ApplicationRecord
end

app/models/gene.rb
class Gene < ApplicationRecord

  def to_fasta( seqid, sequence, num )
    output  = ""
    output += ">#{seqid}\n"
    sequence.split("").each_with_index do |n, i|
      if (i + 1) % num == 0
        output += "#{n}\n"
      else
        output += "#{n}"
      end
    end
    return output
  end



  private

  def to_fasta( seqid, sequence, num )
    output  = ""
    output += ">#{seqid}\n"
    sequence.split("").each_with_index do |n, i|
      if (i + 1) % num == 0
        output += "#{n}\n"
      else
        output += "#{n}"
      end
    end
    return output
  end


end

app/models/protein.rb
class Protein < ApplicationRecord
end

app/models/protein_seq.rb
class ProteinSeq < ApplicationRecord
end

app/models/tattribute.rb
class Tattribute < ApplicationRecord
end

app/models/transcript.rb
class Transcript < ApplicationRecord
end

app/models/transcript_seq.rb
class TranscriptSeq < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord

  validates :name, presence: true, length: { maximum: 50 }
  validates :role, presence: true, length: { maximum: 10 }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

end

app/controllers/dbpaths_controller.rb
class DbpathsController < ApplicationController
  before_action :set_dbpath, only: %i[ show edit update destroy ]

  # GET /dbpaths or /dbpaths.json
  def index
#    @dbpaths = Dbpath.find(params[:id])
    @dbpaths = Dbpath.all
#    @dbpaths = Dbpath.select(:id, :abbreviation)
  end

  # GET /dbpaths/1 or /dbpaths/1.json
  def show
    @dbpaths = Dbpath.all
  end

  # GET /dbpaths/new
  def new
    @dbpath = Dbpath.new
  end

  # GET /dbpaths/1/edit
  def edit
  end

  # POST /dbpaths or /dbpaths.json
  def create
    @dbpath = Dbpath.new(dbpath_params)

    respond_to do |format|
      if @dbpath.save
        format.html { redirect_to @dbpath, notice: "Dbpath was successfully created." }
        format.json { render :show, status: :created, location: @dbpath }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @dbpath.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dbpaths/1 or /dbpaths/1.json
  def update
    respond_to do |format|
      if @dbpath.update(dbpath_params)
        format.html { redirect_to @dbpath, notice: "Dbpath was successfully updated." }
        format.json { render :show, status: :ok, location: @dbpath }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @dbpath.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dbpaths/1 or /dbpaths/1.json
  def destroy
    @dbpath.destroy
    respond_to do |format|
      format.html { redirect_to dbpaths_url, notice: "Dbpath was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dbpath
      @dbpath = Dbpath.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def dbpath_params
      params.require(:dbpath).permit(:project_id, :abbreviation, :sequence_type, :db_path)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title = '')
    base_title = "RF Genome Browser"
    if page_title.empty?
      base_title
    else
      page_title + "|" + base_title
    end
  end
end

app/helpers/attributes_helper.rb
module AttributesHelper
end

app/helpers/blast_helper.rb
module BlastHelper
end

app/helpers/dbpaths_helper.rb
module DbpathsHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/genes_helper.rb
module GenesHelper
end

app/helpers/mafft_helper.rb
module MafftHelper
end

app/helpers/proteins_helper.rb
module ProteinsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/tattributes_helper.rb
module TattributesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dbpaths/_form.html.erb
<%= form_with(model: dbpath) do |form| %>
  <% if dbpath.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dbpath.errors.count, "error") %> prohibited this dbpath from being saved:</h2>

      <ul>
        <% dbpath.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :project_id %>
    <%= form.number_field :project_id %>
  </div>

  <div class="field">
    <%= form.label :abbreviation %>
    <%= form.text_field :abbreviation %>
  </div>

  <div class="field">
    <%= form.label :sequence_type %>
    <%= form.text_field :sequence_type %>
  </div>

  <div class="field">
    <%= form.label :db_path %>
    <%= form.text_area :db_path %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/dbpaths/edit.html.erb
<h1>Editing Dbpath</h1>

<%= render 'form', dbpath: @dbpath %>

<%= link_to 'Show', @dbpath %> |
<%= link_to 'Back', dbpaths_path %>

app/views/dbpaths/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dbpaths</h1>

<table>
  <thead>
    <tr>
      <th>Project</th>
      <th>Abbreviation</th>
      <th>Sequence type</th>
      <th>Db path</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dbpaths.each do |dbpath| %>
      <tr>
        <td><%= dbpath.project_id %></td>
        <td><%= dbpath.abbreviation %></td>
        <td><%= dbpath.sequence_type %></td>
        <td><%= dbpath.db_path %></td>
        <td><%= link_to 'Show', dbpath %></td>
        <td><%= link_to 'Edit', edit_dbpath_path(dbpath) %></td>
        <td><%# = link_to 'Destroy', dbpath, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New Dbpath', new_dbpath_path %>

app/views/dbpaths/new.html.erb
<h1>New Dbpath</h1>

<%= render 'form', dbpath: @dbpath %>

<%= link_to 'Back', dbpaths_path %>

app/views/dbpaths/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Project:</strong>
  <%= @dbpath.project_id %>
</p>

<p>
  <strong>Abbreviation:</strong>
  <%= @dbpath.abbreviation %>
</p>

<p>
  <strong>Sequence type:</strong>
  <%= @dbpath.sequence_type %>
</p>

<p>
  <strong>Db path:</strong>
  <%= @dbpath.db_path %>
</p>

<%= link_to 'Edit', edit_dbpath_path(@dbpath) %> |
<%= link_to 'Back', dbpaths_path %>

<select name="pets" multiple size="5">
    <optgroup label="species1">
      <option value="first">First Value</option>
      <option value="second" select>Second Value</option>
      <option value="third">Third Value</option>
    <optgroup label="species2">
      <option value="first">First Value</option>
      <option value="second" select>Second Value</option>
      <option value="third">Third Value</option>
    </optgroup>
</select>